nodeLinker: node-modules
enableGlobalCache: true

# Hoisting limits for React Native
nmHoistingLimits: workspaces

# Package extensions for peer dependencies
packageExtensions:
  "react-native@*":
    peerDependencies:
      "@babel/core": "*"
      "@babel/runtime": "*"
  "@react-native-community/cli-platform-android@*":
    peerDependencies:
      "@react-native/gradle-plugin": "*"
