// Generated by scripts/write-quereus-version.mjs from the installed @quereus/quereus. Do not edit:
// `yarn workspace @optimystic/quereus-plugin-optimystic build` rewrites it.
export const QUEREUS_VERSION = '4.20.0';
